name: Mobile | CI EAS update

on:
  push:
    branches:
      - main
    paths-ignore:
      - "apps/landing"
      - "apps/desktop"
      - "apps/inbox"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup pnpm v7
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: pnpm -F common install && pnpm -F common build &&  pnpm -F mobile install
        shell: bash

      - name: Build project
        run: pnpm -F mobile build

      - name: Run update
        working-directory: packages/mobile
        run: eas update --auto -p ios
        env:
          EXPO_UPDATES_URL: ${{ secrets.EXPO_UPDATES_URL }}
          EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}
          API_ENDPOINT: ${{ secrets.PRODUCTION_API_BASE_URL }}
          WEB_APP_ENDPOINT: ${{ secrets.PRODUCTION_WEB_APP_BASE_URL }}
          PUSHER_KEY: ${{ secrets.PRODUCTION_PUSHER_KEY }}
          CLOUDFLARE_ACCOUNT_HASH: ${{ secrets.CLOUDFLARE_ACCOUNT_HASH }}
